#
# ░█████╗░██████╗░███╗░░░███╗░█████╗░██████╗░░██████╗░██╗░░░░░░░██╗██╗████████╗░█████╗░██╗░░██╗███████╗██████╗░
# ██╔══██╗██╔══██╗████╗░████║██╔══██╗██╔══██╗██╔════╝░██║░░██╗░░██║██║╚══██╔══╝██╔══██╗██║░░██║██╔════╝██╔══██╗
# ███████║██████╔╝██╔████╔██║██║░░██║██████╔╝╚█████╗░░╚██╗████╗██╔╝██║░░░██║░░░██║░░╚═╝███████║█████╗░░██████╔╝
# ██╔══██║██╔══██╗██║╚██╔╝██║██║░░██║██╔══██╗░╚═══██╗░░████╔═████║░██║░░░██║░░░██║░░██╗██╔══██║██╔══╝░░██╔══██╗
# ██║░░██║██║░░██║██║░╚═╝░██║╚█████╔╝██║░░██║██████╔╝░░╚██╔╝░╚██╔╝░██║░░░██║░░░╚█████╔╝██║░░██║███████╗██║░░██║
# ╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░╚════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝
#
# Leave a rating on spigot!
# Make sure to join our discord server!
# Discord: https://discord.gg/vHqQfsF
#

messages:
  noPermission: '&cYou don''t have permission!'

# Sounds List:
# https://pastebin.com/Mg1TsrbG
sounds:
  onArmorChange:
    name: BLOCK_LAVA_POP
    volume: 5.0
    pitch: 1.0
    
# Permission List:
# - armorswitcher.*
# - armorswitcher.helmet
# - armorswitcher.chestplate
# - armorswitcher.leggings
# - armorswitcher.boots
use-permission: false